Updated units in locations
tbeswick96/DCG pull request #5
Opened 2019-05-10 11:18 UTC by AnAngrySalad1

- Significantly upped numbers of ai in locations, too often do we get into a town and capture it having engaged all the enemies on the outside.

2019-05-10 11:33 UTC, tbeswick96 requested changes

2019-05-10 11:33 UTC, tbeswick96 commented on addons/occupy/functions/fnc_setOccupied.sqf
> +GVAR(location) = [_name,_center,_,_type]; // set as occupied location
'_' looks like an error

2019-05-10 11:49 UTC, AnAngrySalad1 commented on addons/occupy/functions/fnc_setOccupied.sqf
> +GVAR(location) = [_name,_center,_,_type]; // set as occupied location
I dont think i changed that? Or is this something you've spotted

2019-05-10 11:54 UTC, tbeswick96 commented on addons/occupy/functions/fnc_setOccupied.sqf
> +GVAR(location) = [_name,_center,_,_type]; // set as occupied location
It's in the pull request as a change, probably a misclick or something

2019-05-10 11:55 UTC, AnAngrySalad1 commented on addons/occupy/functions/fnc_setOccupied.sqf
> +GVAR(location) = [_name,_center,_,_type]; // set as occupied location
ok then my bad

2019-05-29 13:28 UTC, tbeswick96 commented
Resolved in files directly

2019-05-29 13:28 UTC, closed without merging